# Generated by Django 4.2 on 2024-03-23 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pin',
            name='response',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
