# Generated by Django 4.2 on 2024-03-23 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinboard', '0002_alter_pin_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pin',
            name='submitter',
            field=models.CharField(default='Unknown'),
        ),
    ]
