# Generated by Django 4.2 on 2023-11-04 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='curatedimage',
            old_name='tweetURL',
            new_name='tweet_url',
        ),
    ]
