# Generated by Django 4.2 on 2023-11-04 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curation', '0002_rename_tweeturl_curatedimage_tweet_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curatedimage',
            name='image',
            field=models.ImageField(default=None, upload_to='media/curated_image/'),
        ),
        migrations.AlterField(
            model_name='curatedimage',
            name='tweet_url',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
