# Generated by Django 4.2 on 2023-11-04 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curation', '0003_alter_curatedimage_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtistNickname',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_names', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='curatedimage',
            name='display_names',
            field=models.ManyToManyField(to='curation.artistnickname'),
        ),
    ]
