# Generated by Django 4.2 on 2023-11-04 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curation', '0004_artistnickname_curatedimage_display_names'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ArtistNickname',
            new_name='DisplayName',
        ),
        migrations.RenameField(
            model_name='displayname',
            old_name='display_names',
            new_name='display_name',
        ),
    ]
