# Generated by Django 4.2 on 2023-11-25 17:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('curation', '0007_curatedimage_nsfw_curatedimage_private'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='tagged_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
