# Generated by Django 4.2 on 2023-11-25 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curation', '0008_tag_tagged_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='artist_name',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AlterField(
            model_name='displayname',
            name='display_name',
            field=models.CharField(default='Unknown', max_length=255),
        ),
    ]
