# Generated by Django 4.2 on 2023-07-29 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_useraccount_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='profile_image_url',
            field=models.CharField(null=True),
        ),
    ]
