# Generated by Django 4.2 on 2023-08-09 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_useraccount_profile_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='profile_image',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
    ]
